### ISSUE TITLE
What does line 64 do in app.js?

### ISSUE THREAD

**Issue by Kupie** [juliotec/NoDevFee#2]
I see this in the source:

`data.write(devFee > 0 && getRandomInt(1, 100 / devFee) == 1 ? "0x383a03BABF570A066CF15E48FCfDF147d7DB57Cf" : myEthaddress, ethIndex)`

Just wondering, if this for writing the devfee to juliotec's wallet if it's greater than 0?
https://github.com/juliotec/NoDevFee/blob/master/NoDevFee/app.js#L64

**Comment by juliotec** [comment]
if you put 0 devfee the shares will be all of your eth address if not that dev fee will be to 0x383a03BABF570A066CF15E48FCfDF147d7DB57Cf
, but you can chage that as you want

you can delete the line an put only this
data.write(myEthaddress, ethIndex)

all the dev fee will be to you

**Comment by Kupie** [comment]
Thanks juliotec!

And thanks for making this, an open source solution to my blocks being sent to some millionaire
