### ISSUE TITLE
Verify working status?

### ISSUE THREAD

**Issue by btothec** [juliotec/NoDevFee#3]
I am trying to verify the status of this. I have set it up per directions, and I am mining and passing shares as it should be. However I left the dev fee at 20 and I have been trying to find the shares using the wallet that is listed in the app.js file and I cannot see it as actually sending shares to that wallet. I have tried both the pre-built package as well as the linux version. I am using gminer / flexpool if that matters. Also was curious if I could put this on a local machine and point several mining rigs at it for it to function as kind of a proxy.

**Comment by juliotec** [comment]
Yes its a proxy, it will create a file o show you when the devfee started and which eth changed, i have not tested with gminner, we need check which devfee ports is using gminner
