### ISSUE TITLE
Wow dude

### ISSUE THREAD

**Issue by BlueEyesDev** [juliotec/NoDevFee#5]

**Comment by Kupie** [comment]
It's already talked about here dummy:

https://github.com/juliotec/NoDevFee/issues/2

**Comment by juliotec** [comment]
> Why did you put your address when it is a copy of mine which or I have not put my address in replacement ? because it is even more the devfee of the mining software but directly your address wow Line 64 in app.js https://github.com/BlueEyesDev/PhoenixMiner-NoDevFee

Copy of you? jajaja .
I dont know who you are i write all me code by mine self
